version: "3.5"
networks:
  reseau:
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - 8081:8080
      - 50000:50000
    networks:
      - reseau
  gitlab:
    image: gitlab/gitlab-ce:latest
    restart: always
    container_name: gitlabce
    environment: 
      GITLAB_OMNIBUS_CONFIG: |
      external_url 'https://gitlab.example.com'
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    networks:
      - reseau
